name: prettier

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Cache Deno dependencies
        run: deno cache --lock=deno.lock

      - name: Run prettier -check
        run: |
          deno run -A npm:prettier --check .
