name: prettier

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deno install
      run: curl -fsSL https://deno.land/x/install/install.sh | sh

    - name: Cache Deno dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/deno
        key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}
        restore-keys: |
          ${{ runner.os }}-deno-

    - name: Run Deno cache
      run: deno cache --lock=deno.lock
